---
layout: plainer
title: Create a simple documentation workflow and publication process
---

== Quick step-by-step guide


. Precondition, get a user account on github (to follow along with this demo, start at https://github.com, there is a free option)
. Browse to https://github.com/asciidoctor/jekyll-asciidoc-quickstart
. Click the green 'Use this template' button
. Pick 'create a new repository' on the drop-down page that appears
. Enter your Github username or your organization name under the dropdown in the 'Owner' column
. Enter a repository name for your documentation repository
. Enter an optional description for the repo
. Choose the radio button for 'public' unless you want to make the repo private
. Click the green 'Create repository from template'
. Your new template-clone repository opens to the README.adoc
. Click on 'Settings' on top toolbar
. Click on 'Pages' on left navbar
. Under the Source heading, select the 'GitHub Actions' option
. Notice that 'Jekyll' is pre-selected under 'use a suggested workflow...'
. Click 'configure' to create the prepopulated jekyll.yml config file
. Click the green 'Commit changes...' 
. Click Actions on top toobar 
. Watch the build/deploy workflow (for details, click on 'build' or 'deploy')
. Scroll back to the top of 'Github Pages' where you will see a 'Visit site' button. Click it.
. The Quickstart page appears, hosted in the repo you created.
. If you open index.adoc for edits, add a sentence somewhere and commit the change, the auto-republication workflow will begin. 
. Click on 'actions' on the top toolbar to track the process. 
. When the process finishes, revisit the site and you should see the changes you made.
. To create 'spaces' (in Confluence terminology), create a 'doc' directory at the same level as the index.adoc
. To create 'pages', add a newfile.adoc file in the 'doc' directory
. Edit index.adoc to include a cross-reference to the new file: xref:doc/newfile.adoc
. When the site auto-publish workflow completes, the new link in index.adoc will take you to the new 'page' in the 'doc' space.

=== References and Links
https://asciidoctor.org/ +
http://themes.asciidoctor.org/preview/ <- Writer's guide +
https://docs.asciidoctor.org/asciidoc/latest/directives/include/ +
https://docs.asciidoctor.org/asciidoc/latest/docinfo/ <- custom content into head, header, or footer +
https://powerman.name/doc/asciidoc-827[] +
https://asciidoc-wg.eclipse.org/ +
https://blog.jread.com/auto-build-and-host-pretty-html-documentation-using-asciidoc-github-pages-github-actions-758a03f93d7d <- readme.md with asciidoc pages +
https://matthewjamestaylor.com/holy-grail-layout <- 'holy grail 3 column responsive layout' +
https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/ +
https://jekyllrb.com/docs/step-by-step/07-assets/ <- including css, images, js, _sass +
https://mattrighetti.com/2023/02/22/asciidoc-liquid-and-jekyll <- +
https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/ <- side-by-side examples of markdown and asciidoc syntax +
https://github.com/asciidoctor/kramdown-asciidoc[markdown to asciidoc] <- Kramdown AsciiDoc (Markdown to AsciiDoc) +
https://github.com/opendevise/downdoc[asciidoc to markdown] +
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll +



